name: sublime

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  linux:
    strategy:
      matrix:
        include:
          - ubuntu_ver: 22.04
    runs-on: ubuntu-${{ matrix.ubuntu_ver }}
    timeout-minutes: 45
    if: always()
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wget curl aria2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          VERSION=${VERSION//\//}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Download sublime
        run: |
          # merge
          aria2c https://www.sublimemerge.com/download_thanks?target=win-x64
          aria2c https://www.sublimemerge.com/download_thanks?target=win-x64-portable
          aria2c https://www.sublimemerge.com/download_thanks?target=x64-deb
          aria2c https://www.sublimemerge.com/download_thanks?target=x64-tar
          # text
          aria2c http://www.sublimetext.com/download_thanks?target=win-x64
          aria2c http://www.sublimetext.com/download_thanks?target=win-x64-portable
          aria2c http://www.sublimetext.com/download_thanks?target=x64-deb
          aria2c http://www.sublimetext.com/download_thanks?target=x64-tar
      - name: Upload 
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          path: sublime-*.*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: sublime-*.*
